### PR TITLE
License request

### PR DESCRIPTION
**Pull request by paulriggs2**

### CODE REVIEW

**Comment by ERT78US** [comment]
Serial Number: Next Available Please
Company Name: ADUSEA Inc.
Name of person registering: Eugen Toma
Link to company: https://adusea.com
Description of use: Custom Plane Carrier Board
Git name of the person filling this in: ADUSEA-ERT

**Comment by paulriggs2** [comment]
@proficnc please merge, thank you

**Comment by proficnc** [comment]
merged

**Comment by paulriggs2** [comment]
@proficnc this is marked merged but my request doesn't seem to have made it into the main branch.

**Comment by proficnc** [comment]
Reopening it.. will follow up and figure out what went wrong

**Pull request merged**
